
package com.siebel.ordermanagement.order.details;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderDetailWebService", targetNamespace = "http://siebel.com/OrderManagement/Order/Details", wsdlLocation = "http://localhost/wsdl/OrderDetailWebService.wsdl")
public class OrderDetailWebService
    extends Service
{

    private final static URL ORDERDETAILWEBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/OrderDetailWebService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ORDERDETAILWEBSERVICE_WSDL_LOCATION = url;
    }

    public OrderDetailWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderDetailWebService() {
        super(ORDERDETAILWEBSERVICE_WSDL_LOCATION, new QName("http://siebel.com/OrderManagement/Order/Details", "OrderDetailWebService"));
    }

    /**
     * 
     * @return
     *     returns OrderDetailUDSPort
     */
    @WebEndpoint(name = "OrderDetailUDSPort")
    public OrderDetailUDSPort getOrderDetailUDSPort() {
        return (OrderDetailUDSPort)super.getPort(new QName("http://siebel.com/OrderManagement/Order/Details", "OrderDetailUDSPort"), OrderDetailUDSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderDetailUDSPort
     */
    @WebEndpoint(name = "OrderDetailUDSPort")
    public OrderDetailUDSPort getOrderDetailUDSPort(WebServiceFeature... features) {
        return (OrderDetailUDSPort)super.getPort(new QName("http://siebel.com/OrderManagement/Order/Details", "OrderDetailUDSPort"), OrderDetailUDSPort.class, features);
    }

}
