
package com.siebel.ordermanagement.order.details;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderDetailUDSPort", targetNamespace = "http://siebel.com/OrderManagement/Order/Details")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.order.details.ObjectFactory.class,
    com.siebel.ordermanagement.order.details.data.query.ObjectFactory.class,
    com.siebel.ordermanagement.order.details.data.id.ObjectFactory.class,
    com.siebel.ordermanagement.order.details.data.data.ObjectFactory.class
})
public interface OrderDetailUDSPort {


    /**
     * 
     * @param orderDetailQueryPageInput
     * @return
     *     returns com.siebel.ordermanagement.order.details.OrderDetailQueryPageOutput
     */
    @WebMethod(operationName = "OrderDetailQueryPage", action = "document/http://siebel.com/OrderManagement/Order/Details:OrderDetailQueryPage")
    @WebResult(name = "OrderDetailQueryPage_Output", targetNamespace = "http://siebel.com/OrderManagement/Order/Details", partName = "OrderDetailQueryPage_Output")
    public OrderDetailQueryPageOutput orderDetailQueryPage(
        @WebParam(name = "OrderDetailQueryPage_Input", targetNamespace = "http://siebel.com/OrderManagement/Order/Details", partName = "OrderDetailQueryPage_Input")
        OrderDetailQueryPageInput orderDetailQueryPageInput);

    /**
     * 
     * @param orderDetailUpdateInput
     * @return
     *     returns com.siebel.ordermanagement.order.details.OrderDetailUpdateOutput
     */
    @WebMethod(operationName = "OrderDetailUpdate", action = "document/http://siebel.com/OrderManagement/Order/Details:OrderDetailUpdate")
    @WebResult(name = "OrderDetailUpdate_Output", targetNamespace = "http://siebel.com/OrderManagement/Order/Details", partName = "OrderDetailUpdate_Output")
    public OrderDetailUpdateOutput orderDetailUpdate(
        @WebParam(name = "OrderDetailUpdate_Input", targetNamespace = "http://siebel.com/OrderManagement/Order/Details", partName = "OrderDetailUpdate_Input")
        OrderDetailUpdateInput orderDetailUpdateInput);

}
