
package com.siebel.ordermanagement.quote.psp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CalculatePricePort", targetNamespace = "http://siebel.com/OrderManagement/Quote/PSP")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.quote.psp.ObjectFactory.class,
    com.siebel.ordermanagement.quote.data.ObjectFactory.class
})
public interface CalculatePricePort {


    /**
     * 
     * @param calculatePriceInput
     * @return
     *     returns com.siebel.ordermanagement.quote.psp.CalculatePriceOutput
     */
    @WebMethod(operationName = "CalculatePrice", action = "document/http://siebel.com/OrderManagement/Quote/PSP:CalculatePrice")
    @WebResult(name = "CalculatePrice_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote/PSP", partName = "CalculatePrice_Output")
    public CalculatePriceOutput calculatePrice(
        @WebParam(name = "CalculatePrice_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote/PSP", partName = "CalculatePrice_Input")
        CalculatePriceInput calculatePriceInput);

}
