
package com.siebel.ordermanagement.quote.psp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CalculatePriceWS", targetNamespace = "http://siebel.com/OrderManagement/Quote/PSP", wsdlLocation = "http://localhost/wsdl/CalculatePriceWS.wsdl")
public class CalculatePriceWS
    extends Service
{

    private final static URL CALCULATEPRICEWS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/CalculatePriceWS.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CALCULATEPRICEWS_WSDL_LOCATION = url;
    }

    public CalculatePriceWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatePriceWS() {
        super(CALCULATEPRICEWS_WSDL_LOCATION, new QName("http://siebel.com/OrderManagement/Quote/PSP", "CalculatePriceWS"));
    }

    /**
     * 
     * @return
     *     returns CalculatePricePort
     */
    @WebEndpoint(name = "CalculatePricePort")
    public CalculatePricePort getCalculatePricePort() {
        return (CalculatePricePort)super.getPort(new QName("http://siebel.com/OrderManagement/Quote/PSP", "CalculatePricePort"), CalculatePricePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatePricePort
     */
    @WebEndpoint(name = "CalculatePricePort")
    public CalculatePricePort getCalculatePricePort(WebServiceFeature... features) {
        return (CalculatePricePort)super.getPort(new QName("http://siebel.com/OrderManagement/Quote/PSP", "CalculatePricePort"), CalculatePricePort.class, features);
    }

}
