
package com.siebel.ordermanagement.quote.psp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CheckQuoteEligibilityCompatibilityPort", targetNamespace = "http://siebel.com/OrderManagement/Quote/PSP")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.quote.data.projectedasset.ObjectFactory.class,
    com.siebel.ordermanagement.quote.psp.ObjectFactory.class,
    com.siebel.ordermanagement.quote.data.ObjectFactory.class
})
public interface CheckQuoteEligibilityCompatibilityPort {


    /**
     * 
     * @param checkQuoteEligibilityCompatibilityInput
     * @return
     *     returns com.siebel.ordermanagement.quote.psp.CheckQuoteEligibilityCompatibilityOutput
     */
    @WebMethod(operationName = "CheckQuoteEligibilityCompatibility", action = "document/http://siebel.com/OrderManagement/Quote/PSP:CheckQuoteEligibilityCompatibility")
    @WebResult(name = "CheckQuoteEligibilityCompatibility_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote/PSP", partName = "CheckQuoteEligibilityCompatibility_Output")
    public CheckQuoteEligibilityCompatibilityOutput checkQuoteEligibilityCompatibility(
        @WebParam(name = "CheckQuoteEligibilityCompatibility_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote/PSP", partName = "CheckQuoteEligibilityCompatibility_Input")
        CheckQuoteEligibilityCompatibilityInput checkQuoteEligibilityCompatibilityInput);

}
