
package com.siebel.ordermanagement.quote.psp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EligibilityCompatibility", targetNamespace = "http://siebel.com/OrderManagement/Quote/PSP", wsdlLocation = "http://localhost/wsdl/QuoteEligibilityCompatibility.wsdl")
public class EligibilityCompatibility
    extends Service
{

    private final static URL ELIGIBILITYCOMPATIBILITY_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/QuoteEligibilityCompatibility.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ELIGIBILITYCOMPATIBILITY_WSDL_LOCATION = url;
    }

    public EligibilityCompatibility(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EligibilityCompatibility() {
        super(ELIGIBILITYCOMPATIBILITY_WSDL_LOCATION, new QName("http://siebel.com/OrderManagement/Quote/PSP", "EligibilityCompatibility"));
    }

    /**
     * 
     * @return
     *     returns CheckQuoteEligibilityCompatibilityPort
     */
    @WebEndpoint(name = "CheckQuoteEligibilityCompatibilityPort")
    public CheckQuoteEligibilityCompatibilityPort getCheckQuoteEligibilityCompatibilityPort() {
        return (CheckQuoteEligibilityCompatibilityPort)super.getPort(new QName("http://siebel.com/OrderManagement/Quote/PSP", "CheckQuoteEligibilityCompatibilityPort"), CheckQuoteEligibilityCompatibilityPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckQuoteEligibilityCompatibilityPort
     */
    @WebEndpoint(name = "CheckQuoteEligibilityCompatibilityPort")
    public CheckQuoteEligibilityCompatibilityPort getCheckQuoteEligibilityCompatibilityPort(WebServiceFeature... features) {
        return (CheckQuoteEligibilityCompatibilityPort)super.getPort(new QName("http://siebel.com/OrderManagement/Quote/PSP", "CheckQuoteEligibilityCompatibilityPort"), CheckQuoteEligibilityCompatibilityPort.class, features);
    }

}
