
package com.siebel.selfservice.common.contact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SelfServiceContact", targetNamespace = "http://siebel.com/SelfService/Common/Contact")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.selfservice.common.contact.query.ObjectFactory.class,
    com.siebel.selfservice.common.contact.data.ObjectFactory.class,
    com.siebel.selfservice.common.contact.id.ObjectFactory.class,
    com.siebel.selfservice.common.contact.ObjectFactory.class
})
public interface SelfServiceContact {


    /**
     * 
     * @param selfServiceContactQueryPageInput
     * @return
     *     returns com.siebel.selfservice.common.contact.SelfServiceContactQueryPageOutput
     */
    @WebMethod(operationName = "SelfServiceContactQueryPage", action = "document/http://siebel.com/SelfService/Common/Contact:SelfServiceContactQueryPage")
    @WebResult(name = "SelfServiceContactQueryPage_Output", targetNamespace = "http://siebel.com/SelfService/Common/Contact", partName = "SelfServiceContactQueryPage_Output")
    public SelfServiceContactQueryPageOutput selfServiceContactQueryPage(
        @WebParam(name = "SelfServiceContactQueryPage_Input", targetNamespace = "http://siebel.com/SelfService/Common/Contact", partName = "SelfServiceContactQueryPage_Input")
        SelfServiceContactQueryPageInput selfServiceContactQueryPageInput);

    /**
     * 
     * @param selfServiceContactExecuteInput
     * @return
     *     returns com.siebel.selfservice.common.contact.SelfServiceContactExecuteOutput
     */
    @WebMethod(operationName = "SelfServiceContactExecute", action = "document/http://siebel.com/SelfService/Common/Contact:SelfServiceContactExecute")
    @WebResult(name = "SelfServiceContactExecute_Output", targetNamespace = "http://siebel.com/SelfService/Common/Contact", partName = "SelfServiceContactExecute_Output")
    public SelfServiceContactExecuteOutput selfServiceContactExecute(
        @WebParam(name = "SelfServiceContactExecute_Input", targetNamespace = "http://siebel.com/SelfService/Common/Contact", partName = "SelfServiceContactExecute_Input")
        SelfServiceContactExecuteInput selfServiceContactExecuteInput);

}
