
package com.siebel.selfservice.common.contact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SelfServiceContact", targetNamespace = "http://siebel.com/SelfService/Common/Contact", wsdlLocation = "http://localhost/wsdl/SelfServiceContact.wsdl")
public class SelfServiceContact_Service
    extends Service
{

    private final static URL SELFSERVICECONTACT_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/SelfServiceContact.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SELFSERVICECONTACT_WSDL_LOCATION = url;
    }

    public SelfServiceContact_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SelfServiceContact_Service() {
        super(SELFSERVICECONTACT_WSDL_LOCATION, new QName("http://siebel.com/SelfService/Common/Contact", "SelfServiceContact"));
    }

    /**
     * 
     * @return
     *     returns SelfServiceContact
     */
    @WebEndpoint(name = "SelfServiceContactPort")
    public SelfServiceContact getSelfServiceContactPort() {
        return (SelfServiceContact)super.getPort(new QName("http://siebel.com/SelfService/Common/Contact", "SelfServiceContactPort"), SelfServiceContact.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SelfServiceContact
     */
    @WebEndpoint(name = "SelfServiceContactPort")
    public SelfServiceContact getSelfServiceContactPort(WebServiceFeature... features) {
        return (SelfServiceContact)super.getPort(new QName("http://siebel.com/SelfService/Common/Contact", "SelfServiceContactPort"), SelfServiceContact.class, features);
    }

}
