
package com.siebel.ordermanagement.promotion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PromotionWebService", targetNamespace = "http://siebel.com/OrderManagement/Promotion", wsdlLocation = "http://localhost/wsdl/PromotionWebService.wsdl")
public class PromotionWebService
    extends Service
{

    private final static URL PROMOTIONWEBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/PromotionWebService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PROMOTIONWEBSERVICE_WSDL_LOCATION = url;
    }

    public PromotionWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PromotionWebService() {
        super(PROMOTIONWEBSERVICE_WSDL_LOCATION, new QName("http://siebel.com/OrderManagement/Promotion", "PromotionWebService"));
    }

    /**
     * 
     * @return
     *     returns PromotionDefinitionPort
     */
    @WebEndpoint(name = "PromotionDefinitionPort")
    public PromotionDefinitionPort getPromotionDefinitionPort() {
        return (PromotionDefinitionPort)super.getPort(new QName("http://siebel.com/OrderManagement/Promotion", "PromotionDefinitionPort"), PromotionDefinitionPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PromotionDefinitionPort
     */
    @WebEndpoint(name = "PromotionDefinitionPort")
    public PromotionDefinitionPort getPromotionDefinitionPort(WebServiceFeature... features) {
        return (PromotionDefinitionPort)super.getPort(new QName("http://siebel.com/OrderManagement/Promotion", "PromotionDefinitionPort"), PromotionDefinitionPort.class, features);
    }

    /**
     * 
     * @return
     *     returns ApplyPromotionPort
     */
    @WebEndpoint(name = "ApplyPromotionPort")
    public ApplyPromotionPort getApplyPromotionPort() {
        return (ApplyPromotionPort)super.getPort(new QName("http://siebel.com/OrderManagement/Promotion", "ApplyPromotionPort"), ApplyPromotionPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApplyPromotionPort
     */
    @WebEndpoint(name = "ApplyPromotionPort")
    public ApplyPromotionPort getApplyPromotionPort(WebServiceFeature... features) {
        return (ApplyPromotionPort)super.getPort(new QName("http://siebel.com/OrderManagement/Promotion", "ApplyPromotionPort"), ApplyPromotionPort.class, features);
    }

    /**
     * 
     * @return
     *     returns UpgradePromotionToQuotePort
     */
    @WebEndpoint(name = "UpgradePromotionToQuotePort")
    public UpgradePromotionToQuotePort getUpgradePromotionToQuotePort() {
        return (UpgradePromotionToQuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/Promotion", "UpgradePromotionToQuotePort"), UpgradePromotionToQuotePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpgradePromotionToQuotePort
     */
    @WebEndpoint(name = "UpgradePromotionToQuotePort")
    public UpgradePromotionToQuotePort getUpgradePromotionToQuotePort(WebServiceFeature... features) {
        return (UpgradePromotionToQuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/Promotion", "UpgradePromotionToQuotePort"), UpgradePromotionToQuotePort.class, features);
    }

    /**
     * 
     * @return
     *     returns GetPromotionCommitmentsPort
     */
    @WebEndpoint(name = "GetPromotionCommitmentsPort")
    public GetPromotionCommitmentsPort getGetPromotionCommitmentsPort() {
        return (GetPromotionCommitmentsPort)super.getPort(new QName("http://siebel.com/OrderManagement/Promotion", "GetPromotionCommitmentsPort"), GetPromotionCommitmentsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPromotionCommitmentsPort
     */
    @WebEndpoint(name = "GetPromotionCommitmentsPort")
    public GetPromotionCommitmentsPort getGetPromotionCommitmentsPort(WebServiceFeature... features) {
        return (GetPromotionCommitmentsPort)super.getPort(new QName("http://siebel.com/OrderManagement/Promotion", "GetPromotionCommitmentsPort"), GetPromotionCommitmentsPort.class, features);
    }

    /**
     * 
     * @return
     *     returns UpgradePromotionToOrderPort
     */
    @WebEndpoint(name = "UpgradePromotionToOrderPort")
    public UpgradePromotionToOrderPort getUpgradePromotionToOrderPort() {
        return (UpgradePromotionToOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/Promotion", "UpgradePromotionToOrderPort"), UpgradePromotionToOrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpgradePromotionToOrderPort
     */
    @WebEndpoint(name = "UpgradePromotionToOrderPort")
    public UpgradePromotionToOrderPort getUpgradePromotionToOrderPort(WebServiceFeature... features) {
        return (UpgradePromotionToOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/Promotion", "UpgradePromotionToOrderPort"), UpgradePromotionToOrderPort.class, features);
    }

}
