
package com.siebel.ordermanagement.quote.quoting;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QuotingWebService", targetNamespace = "http://siebel.com/OrderManagement/Quote/Quoting", wsdlLocation = "http://localhost/wsdl/QuotingWebService.wsdl")
public class QuotingWebService
    extends Service
{

    private final static URL QUOTINGWEBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/QuotingWebService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        QUOTINGWEBSERVICE_WSDL_LOCATION = url;
    }

    public QuotingWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuotingWebService() {
        super(QUOTINGWEBSERVICE_WSDL_LOCATION, new QName("http://siebel.com/OrderManagement/Quote/Quoting", "QuotingWebService"));
    }

    /**
     * 
     * @return
     *     returns QuotingPort
     */
    @WebEndpoint(name = "QuotingPort")
    public QuotingPort getQuotingPort() {
        return (QuotingPort)super.getPort(new QName("http://siebel.com/OrderManagement/Quote/Quoting", "QuotingPort"), QuotingPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuotingPort
     */
    @WebEndpoint(name = "QuotingPort")
    public QuotingPort getQuotingPort(WebServiceFeature... features) {
        return (QuotingPort)super.getPort(new QName("http://siebel.com/OrderManagement/Quote/Quoting", "QuotingPort"), QuotingPort.class, features);
    }

}
