
package com.siebel.ordermanagement.quote.quoting;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QuotingPort", targetNamespace = "http://siebel.com/OrderManagement/Quote/Quoting")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.quote.quoting.ObjectFactory.class,
    com.siebel.ordermanagement.quote.data.ObjectFactory.class
})
public interface QuotingPort {


    /**
     * 
     * @param executeQuotingInput
     * @return
     *     returns com.siebel.ordermanagement.quote.quoting.ExecuteQuotingOutput
     */
    @WebMethod(operationName = "ExecuteQuoting", action = "document/http://siebel.com/OrderManagement/Quote/Quoting:ExecuteQuoting")
    @WebResult(name = "ExecuteQuoting_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote/Quoting", partName = "ExecuteQuoting_Output")
    public ExecuteQuotingOutput executeQuoting(
        @WebParam(name = "ExecuteQuoting_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote/Quoting", partName = "ExecuteQuoting_Input")
        ExecuteQuotingInput executeQuotingInput);

}
