drop table sbl_child_product_ui;
drop table sbl_product_blocks;
drop table sbl_promotion_ui_roots;
drop table sbl_relationship_block;
drop table sbl_attribute_block;
drop table sbl_block;
drop table sbl_product_ui;
drop table sbl_promotion_ui;
drop table sbl_renderer;
