
package com.siebel.ordermanagement.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderItemPort", targetNamespace = "http://siebel.com/OrderManagement/Order")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.order.data.ObjectFactory.class,
    com.siebel.ordermanagement.order.ObjectFactory.class,
    com.siebel.ordermanagement.order.item.data.ObjectFactory.class
})
public interface OrderItemPort {


    /**
     * 
     * @param getOrderItemByIdInput
     * @return
     *     returns com.siebel.ordermanagement.order.GetOrderItemByIdOutput
     */
    @WebMethod(operationName = "GetOrderItemById", action = "document/http://siebel.com/OrderManagement/Order:GetOrderItemById")
    @WebResult(name = "GetOrderItemById_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "GetOrderItemById_Output")
    public GetOrderItemByIdOutput getOrderItemById(
        @WebParam(name = "GetOrderItemById_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "GetOrderItemById_Input")
        GetOrderItemByIdInput getOrderItemByIdInput);

    /**
     * 
     * @param getOrderItemInput
     * @return
     *     returns com.siebel.ordermanagement.order.GetOrderItemOutput
     */
    @WebMethod(operationName = "GetOrderItem", action = "document/http://siebel.com/OrderManagement/Order:GetOrderItem")
    @WebResult(name = "GetOrderItem_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "GetOrderItem_Output")
    public GetOrderItemOutput getOrderItem(
        @WebParam(name = "GetOrderItem_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "GetOrderItem_Input")
        GetOrderItemInput getOrderItemInput);

    /**
     * 
     * @param deleteOrderItemInput
     * @return
     *     returns com.siebel.ordermanagement.order.DeleteOrderItemOutput
     */
    @WebMethod(operationName = "DeleteOrderItem", action = "document/http://siebel.com/OrderManagement/Order:DeleteOrderItem")
    @WebResult(name = "DeleteOrderItem_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "DeleteOrderItem_Output")
    public DeleteOrderItemOutput deleteOrderItem(
        @WebParam(name = "DeleteOrderItem_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "DeleteOrderItem_Input")
        DeleteOrderItemInput deleteOrderItemInput);

    /**
     * 
     * @param insertOrderItemInput
     * @return
     *     returns com.siebel.ordermanagement.order.InsertOrderItemOutput
     */
    @WebMethod(operationName = "InsertOrderItem", action = "document/http://siebel.com/OrderManagement/Order:InsertOrderItem")
    @WebResult(name = "InsertOrderItem_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "InsertOrderItem_Output")
    public InsertOrderItemOutput insertOrderItem(
        @WebParam(name = "InsertOrderItem_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "InsertOrderItem_Input")
        InsertOrderItemInput insertOrderItemInput);

    /**
     * 
     * @param updateOrderItemInput
     * @return
     *     returns com.siebel.ordermanagement.order.UpdateOrderItemOutput
     */
    @WebMethod(operationName = "UpdateOrderItem", action = "document/http://siebel.com/OrderManagement/Order:UpdateOrderItem")
    @WebResult(name = "UpdateOrderItem_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "UpdateOrderItem_Output")
    public UpdateOrderItemOutput updateOrderItem(
        @WebParam(name = "UpdateOrderItem_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "UpdateOrderItem_Input")
        UpdateOrderItemInput updateOrderItemInput);

    /**
     * 
     * @param synchronizeOrderItemInput
     * @return
     *     returns com.siebel.ordermanagement.order.SynchronizeOrderItemOutput
     */
    @WebMethod(operationName = "SynchronizeOrderItem", action = "document/http://siebel.com/OrderManagement/Order:SynchronizeOrderItem")
    @WebResult(name = "SynchronizeOrderItem_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "SynchronizeOrderItem_Output")
    public SynchronizeOrderItemOutput synchronizeOrderItem(
        @WebParam(name = "SynchronizeOrderItem_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "SynchronizeOrderItem_Input")
        SynchronizeOrderItemInput synchronizeOrderItemInput);

}
