
package com.siebel.ordermanagement.order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderWebService", targetNamespace = "http://siebel.com/OrderManagement/Order", wsdlLocation = "http://localhost/wsdl/OrderWebService.wsdl")
public class OrderWebService
    extends Service
{

    private final static URL ORDERWEBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/OrderWebService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ORDERWEBSERVICE_WSDL_LOCATION = url;
    }

    public OrderWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderWebService() {
        super(ORDERWEBSERVICE_WSDL_LOCATION, new QName("http://siebel.com/OrderManagement/Order", "OrderWebService"));
    }

    /**
     * 
     * @return
     *     returns OrderPort
     */
    @WebEndpoint(name = "OrderPort")
    public OrderPort getOrderPort() {
        return (OrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/Order", "OrderPort"), OrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderPort
     */
    @WebEndpoint(name = "OrderPort")
    public OrderPort getOrderPort(WebServiceFeature... features) {
        return (OrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/Order", "OrderPort"), OrderPort.class, features);
    }

    /**
     * 
     * @return
     *     returns OrderItemPort
     */
    @WebEndpoint(name = "OrderItemPort")
    public OrderItemPort getOrderItemPort() {
        return (OrderItemPort)super.getPort(new QName("http://siebel.com/OrderManagement/Order", "OrderItemPort"), OrderItemPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderItemPort
     */
    @WebEndpoint(name = "OrderItemPort")
    public OrderItemPort getOrderItemPort(WebServiceFeature... features) {
        return (OrderItemPort)super.getPort(new QName("http://siebel.com/OrderManagement/Order", "OrderItemPort"), OrderItemPort.class, features);
    }

}
