
package com.siebel.ordermanagement.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderPort", targetNamespace = "http://siebel.com/OrderManagement/Order")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.order.data.ObjectFactory.class,
    com.siebel.ordermanagement.order.ObjectFactory.class,
    com.siebel.ordermanagement.order.item.data.ObjectFactory.class
})
public interface OrderPort {


    /**
     * 
     * @param synchronizeOrderInput
     * @return
     *     returns com.siebel.ordermanagement.order.SynchronizeOrderOutput
     */
    @WebMethod(operationName = "SynchronizeOrder", action = "document/http://siebel.com/OrderManagement/Order:SynchronizeOrder")
    @WebResult(name = "SynchronizeOrder_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "SynchronizeOrder_Output")
    public SynchronizeOrderOutput synchronizeOrder(
        @WebParam(name = "SynchronizeOrder_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "SynchronizeOrder_Input")
        SynchronizeOrderInput synchronizeOrderInput);

    /**
     * 
     * @param deleteOrderInput
     * @return
     *     returns com.siebel.ordermanagement.order.DeleteOrderOutput
     */
    @WebMethod(operationName = "DeleteOrder", action = "document/http://siebel.com/OrderManagement/Order:DeleteOrder")
    @WebResult(name = "DeleteOrder_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "DeleteOrder_Output")
    public DeleteOrderOutput deleteOrder(
        @WebParam(name = "DeleteOrder_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "DeleteOrder_Input")
        DeleteOrderInput deleteOrderInput);

    /**
     * 
     * @param getOrderByIdInput
     * @return
     *     returns com.siebel.ordermanagement.order.GetOrderByIdOutput
     */
    @WebMethod(operationName = "GetOrderById", action = "document/http://siebel.com/OrderManagement/Order:GetOrderById")
    @WebResult(name = "GetOrderById_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "GetOrderById_Output")
    public GetOrderByIdOutput getOrderById(
        @WebParam(name = "GetOrderById_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "GetOrderById_Input")
        GetOrderByIdInput getOrderByIdInput);

    /**
     * 
     * @param updateOrderInput
     * @return
     *     returns com.siebel.ordermanagement.order.UpdateOrderOutput
     */
    @WebMethod(operationName = "UpdateOrder", action = "document/http://siebel.com/OrderManagement/Order:UpdateOrder")
    @WebResult(name = "UpdateOrder_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "UpdateOrder_Output")
    public UpdateOrderOutput updateOrder(
        @WebParam(name = "UpdateOrder_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "UpdateOrder_Input")
        UpdateOrderInput updateOrderInput);

    /**
     * 
     * @param getOrderInput
     * @return
     *     returns com.siebel.ordermanagement.order.GetOrderOutput
     */
    @WebMethod(operationName = "GetOrder", action = "document/http://siebel.com/OrderManagement/Order:GetOrder")
    @WebResult(name = "GetOrder_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "GetOrder_Output")
    public GetOrderOutput getOrder(
        @WebParam(name = "GetOrder_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "GetOrder_Input")
        GetOrderInput getOrderInput);

    /**
     * 
     * @param insertOrderInput
     * @return
     *     returns com.siebel.ordermanagement.order.InsertOrderOutput
     */
    @WebMethod(operationName = "InsertOrder", action = "document/http://siebel.com/OrderManagement/Order:InsertOrder")
    @WebResult(name = "InsertOrder_Output", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "InsertOrder_Output")
    public InsertOrderOutput insertOrder(
        @WebParam(name = "InsertOrder_Input", targetNamespace = "http://siebel.com/OrderManagement/Order", partName = "InsertOrder_Input")
        InsertOrderInput insertOrderInput);

}
