
package com.siebel.selfservice.common.account;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SelfServiceAccount", targetNamespace = "http://siebel.com/SelfService/Common/Account")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.selfservice.common.account.ObjectFactory.class,
    com.siebel.selfservice.common.account.query.ObjectFactory.class,
    com.siebel.selfservice.common.account.data.ObjectFactory.class,
    com.siebel.selfservice.common.account.id.ObjectFactory.class
})
public interface SelfServiceAccount {


    /**
     * 
     * @param selfServiceAccountQueryPageInput
     * @return
     *     returns com.siebel.selfservice.common.account.SelfServiceAccountQueryPageOutput
     */
    @WebMethod(operationName = "SelfServiceAccountQueryPage", action = "document/http://siebel.com/SelfService/Common/Account:SelfServiceAccountQueryPage")
    @WebResult(name = "SelfServiceAccountQueryPage_Output", targetNamespace = "http://siebel.com/SelfService/Common/Account", partName = "SelfServiceAccountQueryPage_Output")
    public SelfServiceAccountQueryPageOutput selfServiceAccountQueryPage(
        @WebParam(name = "SelfServiceAccountQueryPage_Input", targetNamespace = "http://siebel.com/SelfService/Common/Account", partName = "SelfServiceAccountQueryPage_Input")
        SelfServiceAccountQueryPageInput selfServiceAccountQueryPageInput);

    /**
     * 
     * @param selfServiceAccountExecuteInput
     * @return
     *     returns com.siebel.selfservice.common.account.SelfServiceAccountExecuteOutput
     */
    @WebMethod(operationName = "SelfServiceAccountExecute", action = "document/http://siebel.com/SelfService/Common/Account:SelfServiceAccountExecute")
    @WebResult(name = "SelfServiceAccountExecute_Output", targetNamespace = "http://siebel.com/SelfService/Common/Account", partName = "SelfServiceAccountExecute_Output")
    public SelfServiceAccountExecuteOutput selfServiceAccountExecute(
        @WebParam(name = "SelfServiceAccountExecute_Input", targetNamespace = "http://siebel.com/SelfService/Common/Account", partName = "SelfServiceAccountExecute_Input")
        SelfServiceAccountExecuteInput selfServiceAccountExecuteInput);

}
