
package com.siebel.selfservice.common.account;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SelfServiceAccount", targetNamespace = "http://siebel.com/SelfService/Common/Account", wsdlLocation = "http://localhost/wsdl/SelfServiceAccount.wsdl")
public class SelfServiceAccount_Service
    extends Service
{

    private final static URL SELFSERVICEACCOUNT_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/SelfServiceAccount.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SELFSERVICEACCOUNT_WSDL_LOCATION = url;
    }

    public SelfServiceAccount_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SelfServiceAccount_Service() {
        super(SELFSERVICEACCOUNT_WSDL_LOCATION, new QName("http://siebel.com/SelfService/Common/Account", "SelfServiceAccount"));
    }

    /**
     * 
     * @return
     *     returns SelfServiceAccount
     */
    @WebEndpoint(name = "SelfServiceAccountPort")
    public SelfServiceAccount getSelfServiceAccountPort() {
        return (SelfServiceAccount)super.getPort(new QName("http://siebel.com/SelfService/Common/Account", "SelfServiceAccountPort"), SelfServiceAccount.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SelfServiceAccount
     */
    @WebEndpoint(name = "SelfServiceAccountPort")
    public SelfServiceAccount getSelfServiceAccountPort(WebServiceFeature... features) {
        return (SelfServiceAccount)super.getPort(new QName("http://siebel.com/SelfService/Common/Account", "SelfServiceAccountPort"), SelfServiceAccount.class, features);
    }

}
