
package com.siebel.selfservice.common.accountbillingprofile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SelfServiceAccountBillingProfile", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.selfservice.common.accountbillingprofile.ObjectFactory.class,
    com.siebel.selfservice.common.accountbillingprofile.query.ObjectFactory.class,
    com.siebel.selfservice.common.accountbillingprofile.data.ObjectFactory.class,
    com.siebel.selfservice.common.accountbillingprofile.id.ObjectFactory.class
})
public interface SelfServiceAccountBillingProfile {


    /**
     * 
     * @param selfServiceAccountBillingProfileDeleteInput
     * @return
     *     returns com.siebel.selfservice.common.accountbillingprofile.SelfServiceAccountBillingProfileDeleteOutput
     */
    @WebMethod(operationName = "SelfServiceAccountBillingProfileDelete", action = "document/http://www.siebel.com/SelfService/Common/AccountBillingProfile:SelfServiceAccountBillingProfileDelete")
    @WebResult(name = "SelfServiceAccountBillingProfileDelete_Output", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileDelete_Output")
    public SelfServiceAccountBillingProfileDeleteOutput selfServiceAccountBillingProfileDelete(
        @WebParam(name = "SelfServiceAccountBillingProfileDelete_Input", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileDelete_Input")
        SelfServiceAccountBillingProfileDeleteInput selfServiceAccountBillingProfileDeleteInput);

    /**
     * 
     * @param selfServiceAccountBillingProfileInsertAndSetPrimaryInput
     * @return
     *     returns com.siebel.selfservice.common.accountbillingprofile.SelfServiceAccountBillingProfileInsertAndSetPrimaryOutput
     */
    @WebMethod(operationName = "SelfServiceAccountBillingProfileInsertAndSetPrimary", action = "document/http://www.siebel.com/SelfService/Common/AccountBillingProfile:SelfServiceAccountBillingProfileInsertAndSetPrimary")
    @WebResult(name = "SelfServiceAccountBillingProfileInsertAndSetPrimary_Output", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileInsertAndSetPrimary_Output")
    public SelfServiceAccountBillingProfileInsertAndSetPrimaryOutput selfServiceAccountBillingProfileInsertAndSetPrimary(
        @WebParam(name = "SelfServiceAccountBillingProfileInsertAndSetPrimary_Input", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileInsertAndSetPrimary_Input")
        SelfServiceAccountBillingProfileInsertAndSetPrimaryInput selfServiceAccountBillingProfileInsertAndSetPrimaryInput);

    /**
     * 
     * @param selfServiceAccountBillingProfileExecuteInput
     * @return
     *     returns com.siebel.selfservice.common.accountbillingprofile.SelfServiceAccountBillingProfileExecuteOutput
     */
    @WebMethod(operationName = "SelfServiceAccountBillingProfileExecute", action = "document/http://www.siebel.com/SelfService/Common/AccountBillingProfile:SelfServiceAccountBillingProfileExecute")
    @WebResult(name = "SelfServiceAccountBillingProfileExecute_Output", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileExecute_Output")
    public SelfServiceAccountBillingProfileExecuteOutput selfServiceAccountBillingProfileExecute(
        @WebParam(name = "SelfServiceAccountBillingProfileExecute_Input", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileExecute_Input")
        SelfServiceAccountBillingProfileExecuteInput selfServiceAccountBillingProfileExecuteInput);

    /**
     * 
     * @param selfServiceAccountBillingProfileUpdateInput
     * @return
     *     returns com.siebel.selfservice.common.accountbillingprofile.SelfServiceAccountBillingProfileUpdateOutput
     */
    @WebMethod(operationName = "SelfServiceAccountBillingProfileUpdate", action = "document/http://www.siebel.com/SelfService/Common/AccountBillingProfile:SelfServiceAccountBillingProfileUpdate")
    @WebResult(name = "SelfServiceAccountBillingProfileUpdate_Output", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileUpdate_Output")
    public SelfServiceAccountBillingProfileUpdateOutput selfServiceAccountBillingProfileUpdate(
        @WebParam(name = "SelfServiceAccountBillingProfileUpdate_Input", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileUpdate_Input")
        SelfServiceAccountBillingProfileUpdateInput selfServiceAccountBillingProfileUpdateInput);

    /**
     * 
     * @param selfServiceAccountBillingProfileUpdateAndSetPrimaryInput
     * @return
     *     returns com.siebel.selfservice.common.accountbillingprofile.SelfServiceAccountBillingProfileUpdateAndSetPrimaryOutput
     */
    @WebMethod(operationName = "SelfServiceAccountBillingProfileUpdateAndSetPrimary", action = "document/http://www.siebel.com/SelfService/Common/AccountBillingProfile:SelfServiceAccountBillingProfileUpdateAndSetPrimary")
    @WebResult(name = "SelfServiceAccountBillingProfileUpdateAndSetPrimary_Output", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileUpdateAndSetPrimary_Output")
    public SelfServiceAccountBillingProfileUpdateAndSetPrimaryOutput selfServiceAccountBillingProfileUpdateAndSetPrimary(
        @WebParam(name = "SelfServiceAccountBillingProfileUpdateAndSetPrimary_Input", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileUpdateAndSetPrimary_Input")
        SelfServiceAccountBillingProfileUpdateAndSetPrimaryInput selfServiceAccountBillingProfileUpdateAndSetPrimaryInput);

    /**
     * 
     * @param selfServiceAccountBillingProfileQueryPageInput
     * @return
     *     returns com.siebel.selfservice.common.accountbillingprofile.SelfServiceAccountBillingProfileQueryPageOutput
     */
    @WebMethod(operationName = "SelfServiceAccountBillingProfileQueryPage", action = "document/http://www.siebel.com/SelfService/Common/AccountBillingProfile:SelfServiceAccountBillingProfileQueryPage")
    @WebResult(name = "SelfServiceAccountBillingProfileQueryPage_Output", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileQueryPage_Output")
    public SelfServiceAccountBillingProfileQueryPageOutput selfServiceAccountBillingProfileQueryPage(
        @WebParam(name = "SelfServiceAccountBillingProfileQueryPage_Input", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileQueryPage_Input")
        SelfServiceAccountBillingProfileQueryPageInput selfServiceAccountBillingProfileQueryPageInput);

    /**
     * 
     * @param selfServiceAccountBillingProfileInitInput
     * @return
     *     returns com.siebel.selfservice.common.accountbillingprofile.SelfServiceAccountBillingProfileInitOutput
     */
    @WebMethod(operationName = "SelfServiceAccountBillingProfileInit", action = "document/http://www.siebel.com/SelfService/Common/AccountBillingProfile:SelfServiceAccountBillingProfileInit")
    @WebResult(name = "SelfServiceAccountBillingProfileInit_Output", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileInit_Output")
    public SelfServiceAccountBillingProfileInitOutput selfServiceAccountBillingProfileInit(
        @WebParam(name = "SelfServiceAccountBillingProfileInit_Input", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileInit_Input")
        SelfServiceAccountBillingProfileInitInput selfServiceAccountBillingProfileInitInput);

    /**
     * 
     * @param selfServiceAccountBillingProfileInsertInput
     * @return
     *     returns com.siebel.selfservice.common.accountbillingprofile.SelfServiceAccountBillingProfileInsertOutput
     */
    @WebMethod(operationName = "SelfServiceAccountBillingProfileInsert", action = "document/http://www.siebel.com/SelfService/Common/AccountBillingProfile:SelfServiceAccountBillingProfileInsert")
    @WebResult(name = "SelfServiceAccountBillingProfileInsert_Output", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileInsert_Output")
    public SelfServiceAccountBillingProfileInsertOutput selfServiceAccountBillingProfileInsert(
        @WebParam(name = "SelfServiceAccountBillingProfileInsert_Input", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileInsert_Input")
        SelfServiceAccountBillingProfileInsertInput selfServiceAccountBillingProfileInsertInput);

    /**
     * 
     * @param selfServiceAccountBillingProfileQueryByIdInput
     * @return
     *     returns com.siebel.selfservice.common.accountbillingprofile.SelfServiceAccountBillingProfileQueryByIdOutput
     */
    @WebMethod(operationName = "SelfServiceAccountBillingProfileQueryById", action = "document/http://www.siebel.com/SelfService/Common/AccountBillingProfile:SelfServiceAccountBillingProfileQueryById")
    @WebResult(name = "SelfServiceAccountBillingProfileQueryById_Output", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileQueryById_Output")
    public SelfServiceAccountBillingProfileQueryByIdOutput selfServiceAccountBillingProfileQueryById(
        @WebParam(name = "SelfServiceAccountBillingProfileQueryById_Input", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileQueryById_Input")
        SelfServiceAccountBillingProfileQueryByIdInput selfServiceAccountBillingProfileQueryByIdInput);

    /**
     * 
     * @param selfServiceAccountBillingProfileSetPrimaryInput
     * @return
     *     returns com.siebel.selfservice.common.accountbillingprofile.SelfServiceAccountBillingProfileSetPrimaryOutput
     */
    @WebMethod(operationName = "SelfServiceAccountBillingProfileSetPrimary", action = "document/http://www.siebel.com/SelfService/Common/AccountBillingProfile:SelfServiceAccountBillingProfileSetPrimary")
    @WebResult(name = "SelfServiceAccountBillingProfileSetPrimary_Output", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileSetPrimary_Output")
    public SelfServiceAccountBillingProfileSetPrimaryOutput selfServiceAccountBillingProfileSetPrimary(
        @WebParam(name = "SelfServiceAccountBillingProfileSetPrimary_Input", targetNamespace = "http://www.siebel.com/SelfService/Common/AccountBillingProfile", partName = "SelfServiceAccountBillingProfileSetPrimary_Input")
        SelfServiceAccountBillingProfileSetPrimaryInput selfServiceAccountBillingProfileSetPrimaryInput);

}
