/*<ORACLECOPYRIGHT>
 * Copyright (C) 1994-2012 Oracle and/or its affiliates. All rights reserved.
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 * UNIX is a registered trademark of The Open Group.
 *
 * This software and related documentation are provided under a license agreement
 * containing restrictions on use and disclosure and are protected by intellectual property laws.
 * Except as expressly permitted in your license agreement or allowed by law, you may not use, copy,
 * reproduce, translate, broadcast, modify, license, transmit, distribute, exhibit, perform, publish,
 * or display any part, in any form, or by any means. Reverse engineering, disassembly,
 * or decompilation of this software, unless required by law for interoperability, is prohibited.
 *
 * The information contained herein is subject to change without notice and is not warranted to be error-free.
 * If you find any errors, please report them to us in writing.
 *
 * U.S. GOVERNMENT RIGHTS Programs, software, databases, and related documentation and technical data delivered to U.S.
 * Government customers are "commercial computer software" or "commercial technical data" pursuant to the applicable
 * Federal Acquisition Regulation and agency-specific supplemental regulations.
 * As such, the use, duplication, disclosure, modification, and adaptation shall be subject to the restrictions and
 * license terms set forth in the applicable Government contract, and, to the extent applicable by the terms of the
 * Government contract, the additional rights set forth in FAR 52.227-19, Commercial Computer Software License
 * (December 2007). Oracle America, Inc., 500 Oracle Parkway, Redwood City, CA 94065.
 *
 * This software or hardware is developed for general use in a variety of information management applications.
 * It is not developed or intended for use in any inherently dangerous applications, including applications that
 * may create a risk of personal injury. If you use this software or hardware in dangerous applications,
 * then you shall be responsible to take all appropriate fail-safe, backup, redundancy,
 * and other measures to ensure its safe use. Oracle Corporation and its affiliates disclaim any liability for any
 * damages caused by use of this software or hardware in dangerous applications.
 *
 * This software or hardware and documentation may provide access to or information on content,
 * products, and services from third parties. Oracle Corporation and its affiliates are not responsible for and
 * expressly disclaim all warranties of any kind with respect to third-party content, products, and services.
 * Oracle Corporation and its affiliates will not be responsible for any loss, costs,
 * or damages incurred due to your access to or use of third-party content, products, or services.
 </ORACLECOPYRIGHT>*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 10:15:38 AM BST 
//


package atg.siebel.catalog.mappingfilebindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}siebel-entity"/>
 *         &lt;element ref="{}atg-entity"/>
 *         &lt;element ref="{}atg-repository"/>
 *         &lt;element ref="{}list-of-field-mappings"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "siebelEntity",
    "atgEntity",
    "atgRepository",
    "listOfFieldMappings"
})
@XmlRootElement(name = "entity-mapping")
public class EntityMapping {

    @XmlElement(name = "siebel-entity", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String siebelEntity;
    @XmlElement(name = "atg-entity", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String atgEntity;
    @XmlElement(name = "atg-repository", required = true)
    protected String atgRepository;
    @XmlElement(name = "list-of-field-mappings", required = true)
    protected ListOfFieldMappings listOfFieldMappings;

    /**
     * Gets the value of the siebelEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiebelEntity() {
        return siebelEntity;
    }

    /**
     * Sets the value of the siebelEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiebelEntity(String value) {
        this.siebelEntity = value;
    }

    /**
     * Gets the value of the atgEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtgEntity() {
        return atgEntity;
    }

    /**
     * Sets the value of the atgEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtgEntity(String value) {
        this.atgEntity = value;
    }

    /**
     * Gets the value of the atgRepository property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtgRepository() {
        return atgRepository;
    }

    /**
     * Sets the value of the atgRepository property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtgRepository(String value) {
        this.atgRepository = value;
    }

    /**
     * Gets the value of the listOfFieldMappings property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfFieldMappings }
     *     
     */
    public ListOfFieldMappings getListOfFieldMappings() {
        return listOfFieldMappings;
    }

    /**
     * Sets the value of the listOfFieldMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfFieldMappings }
     *     
     */
    public void setListOfFieldMappings(ListOfFieldMappings value) {
        this.listOfFieldMappings = value;
    }

}
