
package com.siebel.selfservice.common.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SelfServiceUser", targetNamespace = "http://siebel.com/SelfService/Common/User")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.selfservice.common.user.query.ObjectFactory.class,
    com.siebel.selfservice.common.user.ObjectFactory.class,
    com.siebel.selfservice.common.user.id.ObjectFactory.class,
    com.siebel.selfservice.common.user.data.ObjectFactory.class
})
public interface SelfServiceUser {


    /**
     * 
     * @param selfServiceUserQueryPageInput
     * @return
     *     returns com.siebel.selfservice.common.user.SelfServiceUserQueryPageOutput
     */
    @WebMethod(operationName = "SelfServiceUserQueryPage", action = "document/http://siebel.com/SelfService/Common/User:SelfServiceUserQueryPage")
    @WebResult(name = "SelfServiceUserQueryPage_Output", targetNamespace = "http://siebel.com/SelfService/Common/User", partName = "SelfServiceUserQueryPage_Output")
    public SelfServiceUserQueryPageOutput selfServiceUserQueryPage(
        @WebParam(name = "SelfServiceUserQueryPage_Input", targetNamespace = "http://siebel.com/SelfService/Common/User", partName = "SelfServiceUserQueryPage_Input")
        SelfServiceUserQueryPageInput selfServiceUserQueryPageInput);

    /**
     * 
     * @param selfServiceUserExecuteInput
     * @return
     *     returns com.siebel.selfservice.common.user.SelfServiceUserExecuteOutput
     */
    @WebMethod(operationName = "SelfServiceUserExecute", action = "document/http://siebel.com/SelfService/Common/User:SelfServiceUserExecute")
    @WebResult(name = "SelfServiceUserExecute_Output", targetNamespace = "http://siebel.com/SelfService/Common/User", partName = "SelfServiceUserExecute_Output")
    public SelfServiceUserExecuteOutput selfServiceUserExecute(
        @WebParam(name = "SelfServiceUserExecute_Input", targetNamespace = "http://siebel.com/SelfService/Common/User", partName = "SelfServiceUserExecute_Input")
        SelfServiceUserExecuteInput selfServiceUserExecuteInput);

}
