
package com.siebel.selfservice.common.user;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SelfServiceUser", targetNamespace = "http://siebel.com/SelfService/Common/User", wsdlLocation = "http://localhost/wsdl/SelfServiceUser.wsdl")
public class SelfServiceUser_Service
    extends Service
{

    private final static URL SELFSERVICEUSER_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/SelfServiceUser.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SELFSERVICEUSER_WSDL_LOCATION = url;
    }

    public SelfServiceUser_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SelfServiceUser_Service() {
        super(SELFSERVICEUSER_WSDL_LOCATION, new QName("http://siebel.com/SelfService/Common/User", "SelfServiceUser"));
    }

    /**
     * 
     * @return
     *     returns SelfServiceUser
     */
    @WebEndpoint(name = "SelfServiceUserPort")
    public SelfServiceUser getSelfServiceUserPort() {
        return (SelfServiceUser)super.getPort(new QName("http://siebel.com/SelfService/Common/User", "SelfServiceUserPort"), SelfServiceUser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SelfServiceUser
     */
    @WebEndpoint(name = "SelfServiceUserPort")
    public SelfServiceUser getSelfServiceUserPort(WebServiceFeature... features) {
        return (SelfServiceUser)super.getPort(new QName("http://siebel.com/SelfService/Common/User", "SelfServiceUserPort"), SelfServiceUser.class, features);
    }

}
