
package com.siebel.selfservice.common.address;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SelfServiceAddress", targetNamespace = "http://siebel.com/SelfService/Common/Address", wsdlLocation = "http://localhost/wsdl/SelfServiceAddress.wsdl")
public class SelfServiceAddress_Service
    extends Service
{

    private final static URL SELFSERVICEADDRESS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/SelfServiceAddress.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SELFSERVICEADDRESS_WSDL_LOCATION = url;
    }

    public SelfServiceAddress_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SelfServiceAddress_Service() {
        super(SELFSERVICEADDRESS_WSDL_LOCATION, new QName("http://siebel.com/SelfService/Common/Address", "SelfServiceAddress"));
    }

    /**
     * 
     * @return
     *     returns SelfServiceAddress
     */
    @WebEndpoint(name = "SelfServiceAddressPort")
    public SelfServiceAddress getSelfServiceAddressPort() {
        return (SelfServiceAddress)super.getPort(new QName("http://siebel.com/SelfService/Common/Address", "SelfServiceAddressPort"), SelfServiceAddress.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SelfServiceAddress
     */
    @WebEndpoint(name = "SelfServiceAddressPort")
    public SelfServiceAddress getSelfServiceAddressPort(WebServiceFeature... features) {
        return (SelfServiceAddress)super.getPort(new QName("http://siebel.com/SelfService/Common/Address", "SelfServiceAddressPort"), SelfServiceAddress.class, features);
    }

}
