
package com.siebel.selfservice.common.address;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SelfServiceAddress", targetNamespace = "http://siebel.com/SelfService/Common/Address")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.selfservice.common.address.ObjectFactory.class,
    com.siebel.selfservice.common.address.query.ObjectFactory.class,
    com.siebel.selfservice.common.address.data.ObjectFactory.class,
    com.siebel.selfservice.common.address.id.ObjectFactory.class
})
public interface SelfServiceAddress {


    /**
     * 
     * @param selfServiceAddressQueryPageInput
     * @return
     *     returns com.siebel.selfservice.common.address.SelfServiceAddressQueryPageOutput
     */
    @WebMethod(operationName = "SelfServiceAddressQueryPage", action = "document/http://siebel.com/SelfService/Common/Address:SelfServiceAddressQueryPage")
    @WebResult(name = "SelfServiceAddressQueryPage_Output", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressQueryPage_Output")
    public SelfServiceAddressQueryPageOutput selfServiceAddressQueryPage(
        @WebParam(name = "SelfServiceAddressQueryPage_Input", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressQueryPage_Input")
        SelfServiceAddressQueryPageInput selfServiceAddressQueryPageInput);

    /**
     * 
     * @param selfServiceAddressExecuteInput
     * @return
     *     returns com.siebel.selfservice.common.address.SelfServiceAddressExecuteOutput
     */
    @WebMethod(operationName = "SelfServiceAddressExecute", action = "document/http://siebel.com/SelfService/Common/Address:SelfServiceAddressExecute")
    @WebResult(name = "SelfServiceAddressExecute_Output", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressExecute_Output")
    public SelfServiceAddressExecuteOutput selfServiceAddressExecute(
        @WebParam(name = "SelfServiceAddressExecute_Input", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressExecute_Input")
        SelfServiceAddressExecuteInput selfServiceAddressExecuteInput);

    /**
     * 
     * @param selfServiceAddressInsertInput
     * @return
     *     returns com.siebel.selfservice.common.address.SelfServiceAddressInsertOutput
     */
    @WebMethod(operationName = "SelfServiceAddressInsert", action = "document/http://siebel.com/SelfService/Common/Address:SelfServiceAddressInsert")
    @WebResult(name = "SelfServiceAddressInsert_Output", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressInsert_Output")
    public SelfServiceAddressInsertOutput selfServiceAddressInsert(
        @WebParam(name = "SelfServiceAddressInsert_Input", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressInsert_Input")
        SelfServiceAddressInsertInput selfServiceAddressInsertInput);

    /**
     * 
     * @param selfServiceAddressInitInput
     * @return
     *     returns com.siebel.selfservice.common.address.SelfServiceAddressInitOutput
     */
    @WebMethod(operationName = "SelfServiceAddressInit", action = "document/http://siebel.com/SelfService/Common/Address:SelfServiceAddressInit")
    @WebResult(name = "SelfServiceAddressInit_Output", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressInit_Output")
    public SelfServiceAddressInitOutput selfServiceAddressInit(
        @WebParam(name = "SelfServiceAddressInit_Input", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressInit_Input")
        SelfServiceAddressInitInput selfServiceAddressInitInput);

    /**
     * 
     * @param selfServiceAddressUpdateInput
     * @return
     *     returns com.siebel.selfservice.common.address.SelfServiceAddressUpdateOutput
     */
    @WebMethod(operationName = "SelfServiceAddressUpdate", action = "document/http://siebel.com/SelfService/Common/Address:SelfServiceAddressUpdate")
    @WebResult(name = "SelfServiceAddressUpdate_Output", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressUpdate_Output")
    public SelfServiceAddressUpdateOutput selfServiceAddressUpdate(
        @WebParam(name = "SelfServiceAddressUpdate_Input", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressUpdate_Input")
        SelfServiceAddressUpdateInput selfServiceAddressUpdateInput);

    /**
     * 
     * @param selfServiceAddressDeleteInput
     * @return
     *     returns com.siebel.selfservice.common.address.SelfServiceAddressDeleteOutput
     */
    @WebMethod(operationName = "SelfServiceAddressDelete", action = "document/http://siebel.com/SelfService/Common/Address:SelfServiceAddressDelete")
    @WebResult(name = "SelfServiceAddressDelete_Output", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressDelete_Output")
    public SelfServiceAddressDeleteOutput selfServiceAddressDelete(
        @WebParam(name = "SelfServiceAddressDelete_Input", targetNamespace = "http://siebel.com/SelfService/Common/Address", partName = "SelfServiceAddressDelete_Input")
        SelfServiceAddressDeleteInput selfServiceAddressDeleteInput);

}
