
package com.siebel.ordermanagement.catalog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CatalogPort", targetNamespace = "http://siebel.com/OrderManagement/Catalog")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.catalog.data.relatedproducts.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.udspublishcatalog.query.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.productclassattributes.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.productchildren.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.productdetails.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.udspublishcatalog.data.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.categories.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.relatedpromotions.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.category.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.publishcatalog.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.catalog.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.catalogcontext.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.searchableproductclass.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.product.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.categoryproduct.ObjectFactory.class,
    com.siebel.ordermanagement.catalog.data.productattributedomain.ObjectFactory.class
})
public interface CatalogPort {


    /**
     * 
     * @param getSearchParametersInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetSearchParametersOutput
     */
    @WebMethod(operationName = "GetSearchParameters", action = "document/http://siebel.com/OrderManagement/Catalog:GetSearchParameters")
    @WebResult(name = "GetSearchParameters_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetSearchParameters_Output")
    public GetSearchParametersOutput getSearchParameters(
        @WebParam(name = "GetSearchParameters_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetSearchParameters_Input")
        GetSearchParametersInput getSearchParametersInput);

    /**
     * 
     * @param getProductChildrenInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetProductChildrenOutput
     */
    @WebMethod(operationName = "GetProductChildren", action = "document/http://siebel.com/OrderManagement/Catalog:GetProductChildren")
    @WebResult(name = "GetProductChildren_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetProductChildren_Output")
    public GetProductChildrenOutput getProductChildren(
        @WebParam(name = "GetProductChildren_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetProductChildren_Input")
        GetProductChildrenInput getProductChildrenInput);

    /**
     * 
     * @param executeSearchInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.ExecuteSearchOutput
     */
    @WebMethod(operationName = "ExecuteSearch", action = "document/http://siebel.com/OrderManagement/Catalog:ExecuteSearch")
    @WebResult(name = "ExecuteSearch_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "ExecuteSearch_Output")
    public ExecuteSearchOutput executeSearch(
        @WebParam(name = "ExecuteSearch_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "ExecuteSearch_Input")
        ExecuteSearchInput executeSearchInput);

    /**
     * 
     * @param getRelatedPromotionsInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetRelatedPromotionsOutput
     */
    @WebMethod(operationName = "GetRelatedPromotions", action = "document/http://siebel.com/OrderManagement/Catalog:GetRelatedPromotions")
    @WebResult(name = "GetRelatedPromotions_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetRelatedPromotions_Output")
    public GetRelatedPromotionsOutput getRelatedPromotions(
        @WebParam(name = "GetRelatedPromotions_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetRelatedPromotions_Input")
        GetRelatedPromotionsInput getRelatedPromotionsInput);

    /**
     * 
     * @param getSearchOptionsInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetSearchOptionsOutput
     */
    @WebMethod(operationName = "GetSearchOptions", action = "document/http://siebel.com/OrderManagement/Catalog:GetSearchOptions")
    @WebResult(name = "GetSearchOptions_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetSearchOptions_Output")
    public GetSearchOptionsOutput getSearchOptions(
        @WebParam(name = "GetSearchOptions_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetSearchOptions_Input")
        GetSearchOptionsInput getSearchOptionsInput);

    /**
     * 
     * @param getRelatedProductsInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetRelatedProductsOutput
     */
    @WebMethod(operationName = "GetRelatedProducts", action = "document/http://siebel.com/OrderManagement/Catalog:GetRelatedProducts")
    @WebResult(name = "GetRelatedProducts_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetRelatedProducts_Output")
    public GetRelatedProductsOutput getRelatedProducts(
        @WebParam(name = "GetRelatedProducts_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetRelatedProducts_Input")
        GetRelatedProductsInput getRelatedProductsInput);

    /**
     * 
     * @param getCategoryProductsInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetCategoryProductsOutput
     */
    @WebMethod(operationName = "GetCategoryProducts", action = "document/http://siebel.com/OrderManagement/Catalog:GetCategoryProducts")
    @WebResult(name = "GetCategoryProducts_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetCategoryProducts_Output")
    public GetCategoryProductsOutput getCategoryProducts(
        @WebParam(name = "GetCategoryProducts_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetCategoryProducts_Input")
        GetCategoryProductsInput getCategoryProductsInput);

    /**
     * 
     * @param getProductDetailsInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetProductDetailsOutput
     */
    @WebMethod(operationName = "GetProductDetails", action = "document/http://siebel.com/OrderManagement/Catalog:GetProductDetails")
    @WebResult(name = "GetProductDetails_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetProductDetails_Output")
    public GetProductDetailsOutput getProductDetails(
        @WebParam(name = "GetProductDetails_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetProductDetails_Input")
        GetProductDetailsInput getProductDetailsInput);

    /**
     * 
     * @param getProductAttributeDomainInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetProductAttributeDomainOutput
     */
    @WebMethod(operationName = "GetProductAttributeDomain", action = "document/http://siebel.com/OrderManagement/Catalog:GetProductAttributeDomain")
    @WebResult(name = "GetProductAttributeDomain_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetProductAttributeDomain_Output")
    public GetProductAttributeDomainOutput getProductAttributeDomain(
        @WebParam(name = "GetProductAttributeDomain_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetProductAttributeDomain_Input")
        GetProductAttributeDomainInput getProductAttributeDomainInput);

    /**
     * 
     * @param getCategoriesInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetCategoriesOutput
     */
    @WebMethod(operationName = "GetCategories", action = "document/http://siebel.com/OrderManagement/Catalog:GetCategories")
    @WebResult(name = "GetCategories_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetCategories_Output")
    public GetCategoriesOutput getCategories(
        @WebParam(name = "GetCategories_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetCategories_Input")
        GetCategoriesInput getCategoriesInput);

    /**
     * 
     * @param getCatalogCategoriesInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetCatalogCategoriesOutput
     */
    @WebMethod(operationName = "GetCatalogCategories", action = "document/http://siebel.com/OrderManagement/Catalog:GetCatalogCategories")
    @WebResult(name = "GetCatalogCategories_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetCatalogCategories_Output")
    public GetCatalogCategoriesOutput getCatalogCategories(
        @WebParam(name = "GetCatalogCategories_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetCatalogCategories_Input")
        GetCatalogCategoriesInput getCatalogCategoriesInput);

    /**
     * 
     * @param publishCatalogInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.PublishCatalogOutput
     */
    @WebMethod(operationName = "PublishCatalog", action = "document/http://siebel.com/OrderManagement/Catalog:PublishCatalog")
    @WebResult(name = "PublishCatalog_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "PublishCatalog_Output")
    public PublishCatalogOutput publishCatalog(
        @WebParam(name = "PublishCatalog_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "PublishCatalog_Input")
        PublishCatalogInput publishCatalogInput);

    /**
     * 
     * @param getCatalogsInput
     * @return
     *     returns com.siebel.ordermanagement.catalog.GetCatalogsOutput
     */
    @WebMethod(operationName = "GetCatalogs", action = "document/http://siebel.com/OrderManagement/Catalog:GetCatalogs")
    @WebResult(name = "GetCatalogs_Output", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetCatalogs_Output")
    public GetCatalogsOutput getCatalogs(
        @WebParam(name = "GetCatalogs_Input", targetNamespace = "http://siebel.com/OrderManagement/Catalog", partName = "GetCatalogs_Input")
        GetCatalogsInput getCatalogsInput);

}
