
package com.siebel.ordermanagement.catalog;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CatalogWebService", targetNamespace = "http://siebel.com/OrderManagement/Catalog", wsdlLocation = "http://localhost/wsdl/CatalogWebService.wsdl")
public class CatalogWebService
    extends Service
{

    private final static URL CATALOGWEBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/CatalogWebService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CATALOGWEBSERVICE_WSDL_LOCATION = url;
    }

    public CatalogWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogWebService() {
        super(CATALOGWEBSERVICE_WSDL_LOCATION, new QName("http://siebel.com/OrderManagement/Catalog", "CatalogWebService"));
    }

    /**
     * 
     * @return
     *     returns CatalogPort
     */
    @WebEndpoint(name = "CatalogPort")
    public CatalogPort getCatalogPort() {
        return (CatalogPort)super.getPort(new QName("http://siebel.com/OrderManagement/Catalog", "CatalogPort"), CatalogPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatalogPort
     */
    @WebEndpoint(name = "CatalogPort")
    public CatalogPort getCatalogPort(WebServiceFeature... features) {
        return (CatalogPort)super.getPort(new QName("http://siebel.com/OrderManagement/Catalog", "CatalogPort"), CatalogPort.class, features);
    }

    /**
     * 
     * @return
     *     returns CatalogUDSPort
     */
    @WebEndpoint(name = "CatalogUDSPort")
    public CatalogUDSPort getCatalogUDSPort() {
        return (CatalogUDSPort)super.getPort(new QName("http://siebel.com/OrderManagement/Catalog", "CatalogUDSPort"), CatalogUDSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatalogUDSPort
     */
    @WebEndpoint(name = "CatalogUDSPort")
    public CatalogUDSPort getCatalogUDSPort(WebServiceFeature... features) {
        return (CatalogUDSPort)super.getPort(new QName("http://siebel.com/OrderManagement/Catalog", "CatalogUDSPort"), CatalogUDSPort.class, features);
    }

}
