
package com.siebel.service.fs.assets;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AssetManagementComplex", targetNamespace = "http://www.siebel.com/Service/FS/Assets", wsdlLocation = "http://localhost/wsdl/AssetManagementComplex.wsdl")
public class AssetManagementComplex
    extends Service
{

    private final static URL ASSETMANAGEMENTCOMPLEX_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/AssetManagementComplex.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ASSETMANAGEMENTCOMPLEX_WSDL_LOCATION = url;
    }

    public AssetManagementComplex(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetManagementComplex() {
        super(ASSETMANAGEMENTCOMPLEX_WSDL_LOCATION, new QName("http://www.siebel.com/Service/FS/Assets", "AssetManagementComplex"));
    }

    /**
     * 
     * @return
     *     returns AssetManagementComplexPort
     */
    @WebEndpoint(name = "AssetManagementComplexPort")
    public AssetManagementComplexPort getAssetManagementComplexPort() {
        return (AssetManagementComplexPort)super.getPort(new QName("http://www.siebel.com/Service/FS/Assets", "AssetManagementComplexPort"), AssetManagementComplexPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetManagementComplexPort
     */
    @WebEndpoint(name = "AssetManagementComplexPort")
    public AssetManagementComplexPort getAssetManagementComplexPort(WebServiceFeature... features) {
        return (AssetManagementComplexPort)super.getPort(new QName("http://www.siebel.com/Service/FS/Assets", "AssetManagementComplexPort"), AssetManagementComplexPort.class, features);
    }

}
