
package com.siebel.service.fs.assets;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AssetManagementPort", targetNamespace = "http://www.siebel.com/Service/FS/Assets")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.xml.asset_management_io.id.ObjectFactory.class,
    com.siebel.service.fs.assets.ObjectFactory.class,
    com.siebel.xml.asset_management_io.query.ObjectFactory.class,
    com.siebel.xml.asset_management_io.data.ObjectFactory.class
})
public interface AssetManagementPort {


    /**
     * 
     * @param assetManagementUpdateInput
     * @return
     *     returns com.siebel.service.fs.assets.AssetManagementUpdateOutput
     */
    @WebMethod(operationName = "AssetManagementUpdate", action = "document/http://www.siebel.com/Service/FS/Assets:AssetManagementUpdate")
    @WebResult(name = "AssetManagementUpdate_Output", targetNamespace = "http://www.siebel.com/Service/FS/Assets", partName = "AssetManagementUpdate_Output")
    public AssetManagementUpdateOutput assetManagementUpdate(
        @WebParam(name = "AssetManagementUpdate_Input", targetNamespace = "http://www.siebel.com/Service/FS/Assets", partName = "AssetManagementUpdate_Input")
        AssetManagementUpdateInput assetManagementUpdateInput);

    /**
     * 
     * @param assetManagementQueryPageInput
     * @return
     *     returns com.siebel.service.fs.assets.AssetManagementQueryPageOutput
     */
    @WebMethod(operationName = "AssetManagementQueryPage", action = "document/http://www.siebel.com/Service/FS/Assets:AssetManagementQueryPage")
    @WebResult(name = "AssetManagementQueryPage_Output", targetNamespace = "http://www.siebel.com/Service/FS/Assets", partName = "AssetManagementQueryPage_Output")
    public AssetManagementQueryPageOutput assetManagementQueryPage(
        @WebParam(name = "AssetManagementQueryPage_Input", targetNamespace = "http://www.siebel.com/Service/FS/Assets", partName = "AssetManagementQueryPage_Input")
        AssetManagementQueryPageInput assetManagementQueryPageInput);

    /**
     * 
     * @param assetManagementInsertInput
     * @return
     *     returns com.siebel.service.fs.assets.AssetManagementInsertOutput
     */
    @WebMethod(operationName = "AssetManagementInsert", action = "document/http://www.siebel.com/Service/FS/Assets:AssetManagementInsert")
    @WebResult(name = "AssetManagementInsert_Output", targetNamespace = "http://www.siebel.com/Service/FS/Assets", partName = "AssetManagementInsert_Output")
    public AssetManagementInsertOutput assetManagementInsert(
        @WebParam(name = "AssetManagementInsert_Input", targetNamespace = "http://www.siebel.com/Service/FS/Assets", partName = "AssetManagementInsert_Input")
        AssetManagementInsertInput assetManagementInsertInput);

}
