
package com.siebel.service.fs.assets;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AssetManagement", targetNamespace = "http://www.siebel.com/Service/FS/Assets", wsdlLocation = "http://localhost/wsdl/AssetManagement.wsdl")
public class AssetManagement
    extends Service
{

    private final static URL ASSETMANAGEMENT_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/AssetManagement.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ASSETMANAGEMENT_WSDL_LOCATION = url;
    }

    public AssetManagement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetManagement() {
        super(ASSETMANAGEMENT_WSDL_LOCATION, new QName("http://www.siebel.com/Service/FS/Assets", "AssetManagement"));
    }

    /**
     * 
     * @return
     *     returns AssetManagementPort
     */
    @WebEndpoint(name = "AssetManagementPort")
    public AssetManagementPort getAssetManagementPort() {
        return (AssetManagementPort)super.getPort(new QName("http://www.siebel.com/Service/FS/Assets", "AssetManagementPort"), AssetManagementPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetManagementPort
     */
    @WebEndpoint(name = "AssetManagementPort")
    public AssetManagementPort getAssetManagementPort(WebServiceFeature... features) {
        return (AssetManagementPort)super.getPort(new QName("http://www.siebel.com/Service/FS/Assets", "AssetManagementPort"), AssetManagementPort.class, features);
    }

}
