
package com.siebel.ordermanagement.configurator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BeginConfigurationPort", targetNamespace = "http://siebel.com/OrderManagement/Configurator")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.quote.data.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.webchannelobjgroupitems.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfglinkeditems.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractstatus.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractdata.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.webchannelobjstructure.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractrequest.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfgproperties.ObjectFactory.class
})
public interface BeginConfigurationPort {


    /**
     * 
     * @param beginConfigurationInput
     * @return
     *     returns com.siebel.ordermanagement.configurator.BeginConfigurationOutput
     */
    @WebMethod(operationName = "BeginConfiguration", action = "document/http://siebel.com/OrderManagement/Configurator:BeginConfiguration")
    @WebResult(name = "BeginConfiguration_Output", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "BeginConfiguration_Output")
    public BeginConfigurationOutput beginConfiguration(
        @WebParam(name = "BeginConfiguration_Input", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "BeginConfiguration_Input")
        BeginConfigurationInput beginConfigurationInput);

}
