
package com.siebel.ordermanagement.configurator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CfgObjectBrokerPort", targetNamespace = "http://siebel.com/OrderManagement/Configurator")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.quote.data.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.webchannelobjgroupitems.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfglinkeditems.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractstatus.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractdata.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.webchannelobjstructure.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractrequest.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfgproperties.ObjectFactory.class
})
public interface CfgObjectBrokerPort {


    /**
     * 
     * @param getObjDefaultGroupItemsInput
     * @return
     *     returns com.siebel.ordermanagement.configurator.GetObjDefaultGroupItemsOutput
     */
    @WebMethod(operationName = "GetObjDefaultGroupItems", action = "document/http://siebel.com/OrderManagement/Configurator:GetObjDefaultGroupItems")
    @WebResult(name = "GetObjDefaultGroupItems_Output", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "GetObjDefaultGroupItems_Output")
    public GetObjDefaultGroupItemsOutput getObjDefaultGroupItems(
        @WebParam(name = "GetObjDefaultGroupItems_Input", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "GetObjDefaultGroupItems_Input")
        GetObjDefaultGroupItemsInput getObjDefaultGroupItemsInput);

    /**
     * 
     * @param getCfgObjectStructureInput
     * @return
     *     returns com.siebel.ordermanagement.configurator.GetCfgObjectStructureOutput
     */
    @WebMethod(operationName = "GetCfgObjectStructure", action = "document/http://siebel.com/OrderManagement/Configurator:GetCfgObjectStructure")
    @WebResult(name = "GetCfgObjectStructure_Output", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "GetCfgObjectStructure_Output")
    public GetCfgObjectStructureOutput getCfgObjectStructure(
        @WebParam(name = "GetCfgObjectStructure_Input", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "GetCfgObjectStructure_Input")
        GetCfgObjectStructureInput getCfgObjectStructureInput);

    /**
     * 
     * @param getCfgObjectGroupItemsInput
     * @return
     *     returns com.siebel.ordermanagement.configurator.GetCfgObjectGroupItemsOutput
     */
    @WebMethod(operationName = "GetCfgObjectGroupItems", action = "document/http://siebel.com/OrderManagement/Configurator:GetCfgObjectGroupItems")
    @WebResult(name = "GetCfgObjectGroupItems_Output", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "GetCfgObjectGroupItems_Output")
    public GetCfgObjectGroupItemsOutput getCfgObjectGroupItems(
        @WebParam(name = "GetCfgObjectGroupItems_Input", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "GetCfgObjectGroupItems_Input")
        GetCfgObjectGroupItemsInput getCfgObjectGroupItemsInput);

}
