
package com.siebel.ordermanagement.configurator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EndConfigurationPort", targetNamespace = "http://siebel.com/OrderManagement/Configurator")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.quote.data.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.webchannelobjgroupitems.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfglinkeditems.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractstatus.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractdata.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.webchannelobjstructure.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractrequest.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfgproperties.ObjectFactory.class
})
public interface EndConfigurationPort {


    /**
     * 
     * @param endConfigurationInput
     * @return
     *     returns com.siebel.ordermanagement.configurator.EndConfigurationOutput
     */
    @WebMethod(operationName = "EndConfiguration", action = "document/http://siebel.com/OrderManagement/Configurator:EndConfiguration")
    @WebResult(name = "EndConfiguration_Output", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "EndConfiguration_Output")
    public EndConfigurationOutput endConfiguration(
        @WebParam(name = "EndConfiguration_Input", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "EndConfiguration_Input")
        EndConfigurationInput endConfigurationInput);

}
