
package com.siebel.ordermanagement.configurator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProductConfigurator", targetNamespace = "http://siebel.com/OrderManagement/Configurator", wsdlLocation = "http://localhost/wsdl/ProductConfigurator.wsdl")
public class ProductConfigurator
    extends Service
{

    private final static URL PRODUCTCONFIGURATOR_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/ProductConfigurator.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PRODUCTCONFIGURATOR_WSDL_LOCATION = url;
    }

    public ProductConfigurator(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductConfigurator() {
        super(PRODUCTCONFIGURATOR_WSDL_LOCATION, new QName("http://siebel.com/OrderManagement/Configurator", "ProductConfigurator"));
    }

    /**
     * 
     * @return
     *     returns UpdateConfigurationPort
     */
    @WebEndpoint(name = "UpdateConfigurationPort")
    public UpdateConfigurationPort getUpdateConfigurationPort() {
        return (UpdateConfigurationPort)super.getPort(new QName("http://siebel.com/OrderManagement/Configurator", "UpdateConfigurationPort"), UpdateConfigurationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateConfigurationPort
     */
    @WebEndpoint(name = "UpdateConfigurationPort")
    public UpdateConfigurationPort getUpdateConfigurationPort(WebServiceFeature... features) {
        return (UpdateConfigurationPort)super.getPort(new QName("http://siebel.com/OrderManagement/Configurator", "UpdateConfigurationPort"), UpdateConfigurationPort.class, features);
    }

    /**
     * 
     * @return
     *     returns CfgObjectBrokerPort
     */
    @WebEndpoint(name = "CfgObjectBrokerPort")
    public CfgObjectBrokerPort getCfgObjectBrokerPort() {
        return (CfgObjectBrokerPort)super.getPort(new QName("http://siebel.com/OrderManagement/Configurator", "CfgObjectBrokerPort"), CfgObjectBrokerPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CfgObjectBrokerPort
     */
    @WebEndpoint(name = "CfgObjectBrokerPort")
    public CfgObjectBrokerPort getCfgObjectBrokerPort(WebServiceFeature... features) {
        return (CfgObjectBrokerPort)super.getPort(new QName("http://siebel.com/OrderManagement/Configurator", "CfgObjectBrokerPort"), CfgObjectBrokerPort.class, features);
    }

    /**
     * 
     * @return
     *     returns EndConfigurationPort
     */
    @WebEndpoint(name = "EndConfigurationPort")
    public EndConfigurationPort getEndConfigurationPort() {
        return (EndConfigurationPort)super.getPort(new QName("http://siebel.com/OrderManagement/Configurator", "EndConfigurationPort"), EndConfigurationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndConfigurationPort
     */
    @WebEndpoint(name = "EndConfigurationPort")
    public EndConfigurationPort getEndConfigurationPort(WebServiceFeature... features) {
        return (EndConfigurationPort)super.getPort(new QName("http://siebel.com/OrderManagement/Configurator", "EndConfigurationPort"), EndConfigurationPort.class, features);
    }

    /**
     * 
     * @return
     *     returns BeginConfigurationPort
     */
    @WebEndpoint(name = "BeginConfigurationPort")
    public BeginConfigurationPort getBeginConfigurationPort() {
        return (BeginConfigurationPort)super.getPort(new QName("http://siebel.com/OrderManagement/Configurator", "BeginConfigurationPort"), BeginConfigurationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BeginConfigurationPort
     */
    @WebEndpoint(name = "BeginConfigurationPort")
    public BeginConfigurationPort getBeginConfigurationPort(WebServiceFeature... features) {
        return (BeginConfigurationPort)super.getPort(new QName("http://siebel.com/OrderManagement/Configurator", "BeginConfigurationPort"), BeginConfigurationPort.class, features);
    }

}
