
package com.siebel.ordermanagement.configurator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UpdateConfigurationPort", targetNamespace = "http://siebel.com/OrderManagement/Configurator")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.quote.data.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.webchannelobjgroupitems.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfglinkeditems.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractstatus.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractdata.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.webchannelobjstructure.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfginteractrequest.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.ObjectFactory.class,
    com.siebel.ordermanagement.configurator.cfgproperties.ObjectFactory.class
})
public interface UpdateConfigurationPort {


    /**
     * 
     * @param updateConfigurationInput
     * @return
     *     returns com.siebel.ordermanagement.configurator.UpdateConfigurationOutput
     */
    @WebMethod(operationName = "UpdateConfiguration", action = "document/http://siebel.com/OrderManagement/Configurator:UpdateConfiguration")
    @WebResult(name = "UpdateConfiguration_Output", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "UpdateConfiguration_Output")
    public UpdateConfigurationOutput updateConfiguration(
        @WebParam(name = "UpdateConfiguration_Input", targetNamespace = "http://siebel.com/OrderManagement/Configurator", partName = "UpdateConfiguration_Input")
        UpdateConfigurationInput updateConfigurationInput);

}
